<?php
use Illuminate\Foundation\Testing\WithoutMiddleware;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Goutte\Client;
use GuzzleHttp\Client as GuzzleClient;
use App\Special;
use App\Video;

class SnatchTest extends TestCase
{
    protected $client;
    protected $crawler;
    protected $guzzle;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->client = new Client();
        $this->guzzle = new GuzzleClient();
        $this->client->setClient($this->guzzle);
    }

    public function testBilibili()
    {
        $url = 'http://bangumi.bilibili.com/anime/5774';
        $this->crawler = $this->client->request('GET', $url);
        $videos = $this->crawler->filter('.complete-list .v1-bangumi-list-part-child');
//        $videos->each(function ($node, $i) use ($sid) {
//            Video::where('episode', $i + 1)->where('special_id', $sid)->update(['source_uri'=> $node->click()]);
//        });
        $videos->each(function ($node, $i){
            if($i == 0)
            {
                $info = json_decode($this->guzzle->request('GET', 'http://bangumi.bilibili.com/web_api/episode/'.$node->attr('data-episode-id').'.json')->getBody(), true);
                print_r($info['result']['currentEpisode']['avId']);
            }

        });
    }
}
